name: Build dictionary

on:
  push:
    branches:
      - pkg-moegirl
  workflow_dispatch: {}

jobs:
  build-and-publish:
    if: "(contains(github.event_name, 'schedule') || !contains(github.event.commits[0].message, 'ci ckip'))"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: "0"
          path: "toolkit"

      - name: Build dictionary
        run: |
          mkdir $GITHUB_WORKSPACE/artifacts
          docker run -v $GITHUB_WORKSPACE/artifacts:/artifacts -v $GITHUB_WORKSPACE/toolkit:/toolkit archlinux:base-devel bash /toolkit/utils/build.sh

      - name: Release
        shell: bash
        run: |
          export DATE=`date +%Y%m%d`
          wget https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz -O ghr.tgz
          tar xzf ghr.tgz
          ghr_v0.13.0_linux_amd64/ghr -t ${{ secrets.GITHUB_TOKEN }} -u ${GITHUB_REPOSITORY/\/*/} -r ${GITHUB_REPOSITORY/*\//} -c ${GITHUB_SHA} -delete ${DATE} ./artifacts/
